# Powerby 架构组
# server
server:
  tomcat:
    uri-encoding: UTF-8
    # 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹
    #basedir: ${logging.path}
  #端口号
  port: 8088
#
# log
logging:
  file: ${spring.application.name}
  #path: ${user.home}/logs/${spring.application.name}
  path: /data/logs/niudun-console-server

#
#spring
spring:
  application:
    #应用名
    name: niudun
  profiles:
    active: local
  messages:
    basename: message/core/i18n, message/apollo-sys/i18n
  http:
    encoding:
      force: true
      charset: UTF-8
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 500Mb
  jms:
    listener:
      concurrency: 10
      max-concurrency: 200
  datasource:
    druid:
      initial-size: 20
      max-active: 200
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      #max-open-prepared-statements:
      #validation-query:
      #validation-query-timeout:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #max-evictable-idle-time-millis:

      filters: stat,wall,slf4j,config


    url: jdbc:mysql://CheGuo-DB:3306/niudun_console?characterEncoding=UTF8&amp;zeroDateTimeBehavior=convertToNull&amp;useServerPrepStmts=false&amp;rewriteBatchedStatements=true&amp;useCompression=true
    username: devuser
    password: devuser
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  aop:


#mybatis
mybatis-plus:
  mapper-locations: classpath*:mybatis/apollo-sys/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage:  com.cheguo.apollo.sys.biz.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums

cheguo:
  apollo-sys:
    async-task-concurrency-limit: 200
    task-core-pool-size: 4
    task-max-pool-size: 200
    task-queue-capacity: 200
    #集成模式true；非集成模式false
    sso-mode: true
    #不做登录检查的请求url
    login_not_check_url: /api/sys/login;/api/sys/is_login;/api/sys/user/detail
    #不做权限检查的请求url
    function_not_check_url: /api/sys/login;/api/sys/is_login;/api/sys/user/detail

dubbo:
  port: 28080
  registry:
    path: ${user.home}/.dubbo/${spring.application.name}
  provider:
    timeout: 20000
  consumer:
    timeout: 20000

