# Powerby 架构组 spy
# log
logging:
  path: /data/logs/niudun

#
#
spring:
  datasource:
    druid:
      initial-size: 2
    url: jdbc:mysql://CheGuo-DB:3306/niudun_console?characterEncoding=UTF8&amp;zeroDateTimeBehavior=convertToNull&amp;useServerPrepStmts=false&amp;rewriteBatchedStatements=true&amp;useCompression=true
    username: cgw360
    password: cgw_360
  redis:
    password: ZAJKRedis360
    # Redis数据库索引（默认为0）
    database: 0
    port: 6379
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # Redis服务器地址
    host: CheGuo-Registry
    # 连接超时时间（毫秒）
    timeout: 0
  activemq:
    broker-url: failover:(tcp://CheGuo-Registry:61616)?randomize=false&jms.useAsyncSend=true
    user:
    password:


cheguo:
  apollo-sys:
    async-task-concurrency-limit: 10
    task-core-pool-size: 4
    task-max-pool-size: 20
    task-queue-capacity: 100
    validate-resource-function: false
    check_user_login: true
    local:
      loginUrl:
      successUrl:
    cas:
      casServerUrlPrefix: https://cas.cheguo.com
      shiroServerUrlPrefix: https://mm.cheguo.com
      successUrl: https://mm.cheguo.com
      casServerLogoutUrl: https://cas.cheguo.com/logout?service=https://mm.cheguo.com/api/sys/shiro-apollo
      sso-modifypwd-url: https://cas.cheguo.com/modifyPassword
    mq:
      # 支持的模式VIRTUAL_TOPIC或者QUEUE
      mode: VIRTUAL_TOPIC
      persistent: true
      # 1 自动确认
      # 2 客户端确认
      # 3 消息可重复确认
      # 4 单条确认
      ack_mode: 4

      url: tcp://CheGuo-Registry:61616


dubbo:
  #
  # custom
  cheguo:
    # basic-service/ credit-service
    basic-api:
      registry:
        address: zookeeper://cg.common.zk:2181
      group: cgw
      version: 1.3.0
      retries: 0
      check: false
    basic-user:
      registry:
        address: zookeeper://cg.common.zk:2181
      group: cgw
      version: 1.0.0
      retries: 0
      timeout: 10000
    b:
      registry:
        address: zookeeper://cg.b.zk:2181
      group: cgw
      version: 1.3.0
      retries: 0
      timeout: 10000
    c:
      registry:
        address: zookeeper://cg.c.zk:2181
      group: cgw
      version: 1.3.0
      retries: 0
      timeout: 10000
      check: false
    user:
      registry:
        address: zookeeper://cg.user.zk:2181
      group: user
      version: 1.3.0
      retries: 0
      timeout: 10000
